paths:
  path_data: "/scratch/nmoreau/KPIs_challenge/Training_data/Task2_WSI_level/"
  path_output: "/scratch/nmoreau/KPIs_challenge/training_runs/"

hyperparameters:
  fold_num: 0
  use_same_data_as: "/scratch/nmoreau/KPIs_challenge/training_runs/runs_22_07_2024_13_57_17_fold_0_hover/"
  num_workers: 8
  in_channels: 4
  out_channels: 2
  hovermaps: True
  freeze_encoder: False
  freeze_decoder_bin: False
  continue_training: None
  initial_learning_rate: 0.0001
  weight_decay: 0.001
  nb_batch_per_epochs: 50
  nb_epochs: 150
  batch_size: 8
