paths:
  path_data: "/your_directory/data_for_training/"
  path_output: "/your_directory/training_runs/"

hyperparameters:
  fold_num: 0
  use_same_data_as: "/your_directory/training_runs/runs_bin/" #to use the same order of patches during training
  num_workers: 8
  in_channels: 4
  out_channels: 2
  hovermaps: True
  freeze_encoder: False
  freeze_decoder_bin: False
  continue_training: None
  initial_learning_rate: 0.0001
  weight_decay: 0.001
  nb_batch_per_epochs: 50
  nb_epochs: 150
  batch_size: 8
  patch_size: 512
